import "@styles/globals.css";
import '@styles/BgAnimationSquare.scss'
import '@styles/colors.module.scss'
import '@styles/contact.scss'
import '@styles/BgAnimationWaves.scss'
import Navbar from "@components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="w-full m-auto  scroll-smooth">
          <Navbar />
          <div className="">{children}</div>
        </div>
      </body>
    </html>
  );
}
